import { Types } from 'mongoose';
import { ICommonProfile } from '../user/user.interface';
import { IProductComment } from './comment/comment.interface';
import { CategoryType } from '../category/category.interface';
import { productStatus } from './product.constant';

export type ProductStatus = (typeof productStatus)[number];

export type IProduct = {
  _id: Types.ObjectId;
  // Photos - keep as is
  photos: {
    mainPhoto: string;
    others?: string[];
  };
  // Car Details
  title: string;
  maker: string;
  model: string;
  modelCode?: string;
  grade?: string;
  year: number;
  registrationYear?: number;
  productionYear: number;
  stockNumber?: string;
  referenceNumber?: string;
  mileage: number;
  engineSize: string;
  engineCc?: string;
  fuelType: string;
  transmission: string;
  driveType: string;
  steering?: string;
  steeringType?: string;
  seats?: number;
  seatCount?: number;
  bodyType: string;
  color: string;
  vinChassisNumber?: string;
  auctionGrade?: string;
  condition: string;
  price: string;
  location?: string | { city: string; zipCode: number };
  featuresAndOptions?: string[];
  accessories?: string[];
  optionsList?: string[];
  optionsText?: string;
  options?: string;
  additionalOptions?: string;
  internalNote?: string;
  adminNote?: string;
  videoLinks?: string[];
  // System fields
  seller: Types.ObjectId | ICommonProfile;
  sellerType?: string;
  status?: ProductStatus;
  isWatchlisted?: boolean;
  isWishlisted?: boolean;
  comments?: IProductComment[];
  totalComment: number;
  views?: number;
  category?: CategoryType;
  startBid?: Date;
  endBid?: Date;
  minBid?: number;
  isBedded?: boolean;
  highestBid?: number | null;
  totalBids?: number;
  highestBidder: {
    id: string;
    name: string;
    profilePhoto: string;
  };
  isDraft?: boolean;
  isSoldOut?: boolean;
  isAuction?: boolean;
  isWinner?: boolean;
  isFeatured?: boolean;
  createdAt: Date;
};

export type IProductFilterableField = {
  searchTerm: string;
  title: string;
  maker: string;
  model: string;
  modelCode: string;
  grade: string;
  year: string;
  registrationYear?: string;
  productionYear: string;
  stockNumber: string;
  referenceNumber: string;
  mileage: string;
  engineSize: string;
  engineCc: string;
  fuelType: string;
  transmission: string;
  driveType: string;
  steering: string;
  steeringType: string;
  seats: string;
  seatCount: string;
  bodyType: string;
  color: string;
  vinChassisNumber: string;
  auctionGrade: string;
  condition: string;
  price: string;
  location: string;
  accessories: string;
  optionsList: string;
  optionsText: string;
  options: string;
  additionalOptions: string;
  internalNote: string;
  adminNote: string;
  endingSoon: boolean;
  newlyListed: boolean;
  isWinner?: boolean;
  status?: ProductStatus;
  totalBids?: number;
  endBid?: Date;
  minBid?: number;
};
