export const productSearchableFields = [
  'title',
  'maker',
  'model',
  'modelCode',
  'grade',
  'year',
  'registrationYear',
  'productionYear',
  'stockNumber',
  'referenceNumber',
  'mileage',
  'engineSize',
  'engineCc',
  'fuelType',
  'transmission',
  'driveType',
  'steering',
  'steeringType',
  'seats',
  'seatCount',
  'bodyType',
  'color',
  'vinChassisNumber',
  'auctionGrade',
  'condition',
  'price',
  'location',
  'featuresAndOptions',
  'accessories',
  'optionsList',
  'optionsText',
  'options',
  'additionalOptions',
  'internalNote',
  'adminNote',
  'videoLinks',
  'isWinner',
  'isDraft',
  'category',
  'highestBid',
  'createdAt',
  'endBid',
  'endingSoon',
  'isFeatured',
  'status',
];

export const productFilterableFields = [
  'searchTerm',
  'title',
  'maker',
  'model',
  'modelCode',
  'grade',
  'year',
  'registrationYear',
  'productionYear',
  'stockNumber',
  'referenceNumber',
  'mileage',
  'engineSize',
  'engineCc',
  'fuelType',
  'transmission',
  'driveType',
  'steering',
  'steeringType',
  'seats',
  'seatCount',
  'bodyType',
  'color',
  'vinChassisNumber',
  'auctionGrade',
  'condition',
  'price',
  'location',
  'accessories',
  'optionsList',
  'optionsText',
  'options',
  'additionalOptions',
  'internalNote',
  'adminNote',
  'endingSoon',
  'newlyListed',
  'isWinner',
  'isDraft',
  'category',
  'highestBid',
  'createdAt',
  'endBid',
  'mileage',
  'isFeatured',
  'status',
];

export const productStatus = [
  'pending',
  'upcoming',
  'approval',
  'reserve',
  'under_negotiations',
  'sold',
] as const;

export const bodyStyleEnum = [
  'coupe',
  'convertible',
  'hatchback',
  'sedan',
  'suv/crossover',
  'truck',
  'van/minivan',
  'wagon',
];

export const transmissionEnum = ['Automatic', 'Manual'];

export const titleStatusEnum = [
  'clean (CT)',
  'salvage',
  'rebuilt/reconstructed',
  'junk',
  'buyback',
  'bonded',
  'export only',
  'odometer rollback',
  'flood',
  'non-repairable',
];
